### ISSUE TITLE
Upgrade 32 Bit agent to 64 path bug

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/WindowsAgent#206] opened 2021-01-21 10:51 UTC
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  
windows 7 or windows 10
### OCS Inventory information
Windows agent version : 2.05

### Problem's description
When i upgrade a old 32 bit agent (2.0.5.0) to Version 2.8 the x86 path "C:\Program Files (x86)\OCS Inventory Agen" will be used instead of "C:\Program Files\OCS Inventory Agent"
If i uninstall the old one first .. and the install the new one .. the correct 64 bit Path "C:\Program Files\OCS Inventory Agent" will be used

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by charleneauger** [comment] 2021-06-29 14:45
Duplicate of #203

**Closed by charleneauger** 2021-06-29 14:45 UTC
Labels: duplicate
