### ISSUE TITLE
Missing network adapters inventoried

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/WindowsAgent#98] opened 2018-08-27 15:48 UTC
### General information
Operating system :  CentOS 7.4.1708

### OCS Inventory information

- Windows agent version : 2.3.1.1 and 2.4.0.0: Fails
- Windows agent version : 2.1.1.1: OK

### Problem's description
Ipconfig.exe /all shows 4 network adapters but only 2 are registered in the ocs database. I installed ocs agent 2.1.1.1 and it does register all 4 adapters.

- With ocs agent 2.4.0.0 (or 2.3.1.1): http://prntscr.com/kngmue
- With ocs agent 2.1.1.1: http://prntscr.com/kngo8p
- Ipconfig /all: http://prntscr.com/kngqww

**Comment by charleneauger** [comment] 2019-01-07 16:17
Hi @pchamo ,
This issue is a duplicate of #90.
So I close your issue.
Regards,
Charlene Auger

**Closed by charleneauger** 2019-01-07 16:17 UTC
Labels: duplicate
